export const CUSTOMER_ADDRESS_LIST_REQUEST = 'CUSTOMER_ADDRESS_LIST_REQUEST'
export const CUSTOMER_ADDRESS_LIST_SUCCESS = 'CUSTOMER_ADDRESS_LIST_SUCCESS'
export const CUSTOMER_ADDRESS_LIST_FAIL = 'CUSTOMER_ADDRESS_LIST_FAIL'

export const CUSTOMER_ADDRESS_DELETE_REQUEST = 'CUSTOMER_ADDRESS_DELETE_REQUEST'
export const CUSTOMER_ADDRESS_DELETE_SUCCESS = 'CUSTOMER_ADDRESS_DELETE_SUCCESS'
export const CUSTOMER_ADDRESS_DELETE_FAIL = 'CUSTOMER_ADDRESS_DELETE_FAIL'

export const CUSTOMER_ADDRESS_CREATE_REQUEST = 'CUSTOMER_ADDRESS_CREATE_REQUEST'
export const CUSTOMER_ADDRESS_CREATE_SUCCESS = 'CUSTOMER_ADDRESS_CREATE_SUCCESS'
export const CUSTOMER_ADDRESS_CREATE_FAIL = 'CUSTOMER_ADDRESS_CREATE_FAIL'
export const CUSTOMER_ADDRESS_CREATE_RESET = 'CUSTOMER_ADDRESS_CREATE_RESET'

export const CUSTOMER_ADDRESS_UPDATE_REQUEST = 'CUSTOMER_ADDRESS_UPDATE_REQUEST'
export const CUSTOMER_ADDRESS_UPDATE_SUCCESS = 'CUSTOMER_ADDRESS_UPDATE_SUCCESS'
export const CUSTOMER_ADDRESS_UPDATE_FAIL = 'CUSTOMER_ADDRESS_UPDATE_FAIL'
export const CUSTOMER_ADDRESS_UPDATE_RESET = 'CUSTOMER_ADDRESS_UPDATE_RESET'

