export const CART_LIST_REQUEST = 'CART_LIST_REQUEST'
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS'
export const CART_LIST_FAIL = 'CART_LIST_FAIL'
export const CART_LIST_RESET = 'CART_LIST_RESET'

export const CART_ITEM_DELETE_REQUEST = 'CART_ITEM_DELETE_REQUEST'
export const CART_ITEM_DELETE_SUCCESS = 'CART_ITEM_DELETE_SUCCESS'
export const CART_ITEM_DELETE_FAIL = 'CART_ITEM_DELETE_FAIL'

export const CART_ITEM_ADD_REQUEST = 'CART_ITEM_ADD_REQUEST'
export const CART_ITEM_ADD_SUCCESS = 'CART_ITEM_ADD_SUCCESS'
export const CART_ITEM_ADD_FAIL = 'CART_ITEM_ADD_FAIL'
export const CART_ITEM_ADD_RESET = 'CART_ITEM_ADD_RESET'

export const CART_ITEM_UPDATE_REQUEST = 'CART_ITEM_UPDATE_REQUEST'
export const CART_ITEM_UPDATE_SUCCESS = 'CART_ITEM_UPDATE_SUCCESS'
export const CART_ITEM_UPDATE_FAIL = 'CART_ITEM_UPDATE_FAIL'