export const CUSTOMER_ADDRESS_REQUEST = 'CUSTOMER_ADDRESS_REQUEST'
export const CUSTOMER_ADDRESS_SUCCESS = 'CUSTOMER_ADDRESS_SUCCESS'
export const CUSTOMER_ADDRESS_FAIL = 'CUSTOMER_ADDRESS_FAIL'
export const CUSTOMER_ADDRESS_RESET = 'CUSTOMER_ADDRESS_RESET'

