export const CUSTOMER_ADDRESS_REQUEST = 'CUSTOMER_ADDRESS_REQUEST'
export const CUSTOMER_ADDRESS_SUCCESS = 'CUSTOMER_ADDRESS_SUCCESS'
export const CUSTOMER_ADDRESS_FAIL = 'CUSTOMER_ADDRESS_FAIL'
export const CUSTOMER_ADDRESS_RESET = 'CUSTOMER_ADDRESS_RESET'

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST'
export const CART_LIST_SUCCESS = 'CART_LIST_SUCCESS'
export const CART_LIST_FAIL = 'CART_LIST_FAIL'

export const CART_ITEM_DELETE_REQUEST = 'CART_ITEM_DELETE_REQUEST'
export const CART_ITEM_DELETE_SUCCESS = 'CART_ITEM_DELETE_SUCCESS'
export const CART_ITEM_DELETE_FAIL = 'CART_ITEM_DELETE_FAIL'

export const CART_ITEM_UPDATE_REQUEST = 'CART_ITEM_UPDATE_REQUEST'
export const CART_ITEM_UPDATE_SUCCESS = 'CART_ITEM_UPDATE_SUCCESS'
export const CART_ITEM_UPDATE_FAIL = 'CART_ITEM_UPDATE_FAIL'