export const CUSTOMER_ORDER_LIST_REQUEST = 'CUSTOMER_ORDER_LIST_REQUEST'
export const CUSTOMER_ORDER_LIST_SUCCESS = 'CUSTOMER_ORDER_LIST_SUCCESS'
export const CUSTOMER_ORDER_LIST_FAIL = 'CUSTOMER_ORDER_LIST_FAIL'
export const CUSTOMER_ORDER_LIST_RESET = 'CUSTOMER_ORDER_LIST_RESET'

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const CUSTOMER_ORDER_DETAILS_REQUEST = 'CUSTOMER_ORDER_DETAILS_REQUEST'
export const CUSTOMER_ORDER_DETAILS_SUCCESS = 'CUSTOMER_ORDER_DETAILS_SUCCESS'
export const CUSTOMER_ORDER_DETAILS_FAIL = 'CUSTOMER_ORDER_DETAILS_FAIL'
export const CUSTOMER_ORDER_DETAILS_RESET = 'CUSTOMER_ORDER_DETAILS_RESET'

export const ORDER_DETAILS_CREATE_REQUEST = 'ORDER_DETAILS_CREATE_REQUEST'
export const ORDER_DETAILS_CREATE_SUCCESS = 'ORDER_DETAILS_CREATE_SUCCESS'
export const ORDER_DETAILS_CREATE_FAIL = 'ORDER_DETAILS_CREATE_FAIL'
export const ORDER_DETAILS_CREATE_RESET = 'ORDER_DETAILS_CREATE_RESET'

export const UPDATE_COUNTINSTOCK_REQUEST = 'UPDATE_COUNTINSTOCK_REQUEST'
export const UPDATE_COUNTINSTOCK_SUCCESS = 'UPDATE_COUNTINSTOCK_SUCCESS'
export const UPDATE_COUNTINSTOCK_FAIL = 'UPDATE_COUNTINSTOCK_FAIL'
export const UPDATE_COUNTINSTOCK_RESET = 'UPDATE_COUNTINSTOCK_RESET'

//vendor
export const VENDOR_ORDER_DETAILS_LIST_REQUEST = 'VENDOR_ORDER_DETAILS_LIST_REQUEST'
export const VENDOR_ORDER_DETAILS_LIST_SUCCESS = 'VENDOR_ORDER_DETAILS_LIST_SUCCESS'
export const VENDOR_ORDER_DETAILS_LIST_FAIL = 'VENDOR_ORDER_DETAILS_LIST_FAIL'
export const VENDOR_ORDER_DETAILS_LIST_RESET = 'VENDOR_ORDER_DETAILS_LIST_RESET'


//admin
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'