export const VENDOR_LOGIN_REQUEST = 'VENDOR_LOGIN_REQUEST'
export const VENDOR_LOGIN_SUCCESS = 'VENDOR_LOGIN_SUCCESS'
export const VENDOR_LOGIN_FAIL = 'VENDOR_LOGIN_FAIL'
export const VENDOR_LOGOUT = 'VENDOR_LOGOUT'

export const VENDOR_REGISTER_REQUEST = 'VENDOR_REGISTER_REQUEST'
export const VENDOR_REGISTER_SUCCESS = 'VENDOR_REGISTER_SUCCESS'
export const VENDOR_REGISTER_FAIL = 'VENDOR_REGISTER_FAIL'

export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'

export const VENDOR_DETAILS_REQUEST = 'VENDOR_DETAILS_REQUEST'
export const VENDOR_DETAILS_SUCCESS = 'VENDOR_DETAILS_SUCCESS'
export const VENDOR_DETAILS_FAIL = 'VENDOR_DETAILS_FAIL'